using AcademicTrack.Domain.Entities;
using AcademicTrack.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace AcademicTrack.Infrastructure.Persistence;

public static class DbInitializer
{
    public static void Seed(AcademicTrackDbContext context)
    {
        // 1. DDL: Garantizar la creación de tablas e índices de actividades de forma directa e incondicional
        try
        {
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS activity (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ProgramId"" integer NOT NULL,
                    ""Type"" character varying(30) NOT NULL,
                    ""Name"" character varying(300) NOT NULL,
                    ""Date"" date NOT NULL,
                    ""Location"" character varying(200) NULL,
                    ""Responsible"" character varying(150) NOT NULL,
                    ""ParticipatingProfessors"" text NULL,
                    ""ParticipatingStudents"" text NULL,
                    ""Description"" text NULL,
                    CONSTRAINT ""PK_activity"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_activity_programa_ProgramId"" FOREIGN KEY (""ProgramId"")
                        REFERENCES programa (""Id"") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS idx_activity_program ON activity (""ProgramId"");
                CREATE INDEX IF NOT EXISTS idx_activity_type ON activity (""Type"");
                CREATE INDEX IF NOT EXISTS idx_activity_date ON activity (""Date"");

                CREATE TABLE IF NOT EXISTS activity_evidence (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ActivityId"" integer NOT NULL,
                    ""Url"" character varying(500) NOT NULL,
                    ""UploadDate"" date NOT NULL,
                    CONSTRAINT ""PK_activity_evidence"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_activity_evidence_activity_ActivityId"" FOREIGN KEY (""ActivityId"")
                        REFERENCES activity (""Id"") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS idx_activity_evidence_activity ON activity_evidence (""ActivityId"");

                CREATE TABLE IF NOT EXISTS users (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Username"" character varying(50) NOT NULL,
                    ""Email"" character varying(100) NOT NULL,
                    ""PasswordHash"" character varying(255) NOT NULL,
                    ""FullName"" character varying(150) NOT NULL,
                    ""Role"" character varying(50) NOT NULL DEFAULT 'Docente',
                    ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""LastLoginAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_users"" PRIMARY KEY (""Id"")
                );

                CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username ON users (""Username"");
                CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (""Email"");

                CREATE TABLE IF NOT EXISTS roles (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(50) NOT NULL,
                    ""Description"" character varying(250) NULL,
                    ""IsSystemRole"" boolean NOT NULL DEFAULT FALSE,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ""PK_roles"" PRIMARY KEY (""Id"")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS uq_roles_name ON roles (""Name"");

                CREATE TABLE IF NOT EXISTS permissions (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Code"" character varying(50) NOT NULL,
                    ""Name"" character varying(100) NOT NULL,
                    ""Module"" character varying(50) NOT NULL,
                    ""Description"" character varying(250) NULL,
                    CONSTRAINT ""PK_permissions"" PRIMARY KEY (""Id"")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS uq_permissions_code ON permissions (""Code"");

                CREATE TABLE IF NOT EXISTS role_permissions (
                    ""RoleId"" integer NOT NULL,
                    ""PermissionId"" integer NOT NULL,
                    CONSTRAINT ""PK_role_permissions"" PRIMARY KEY (""RoleId"", ""PermissionId""),
                    CONSTRAINT ""FK_role_permissions_roles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES roles (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_role_permissions_permissions_PermissionId"" FOREIGN KEY (""PermissionId"") REFERENCES permissions (""Id"") ON DELETE CASCADE
                );

                ALTER TABLE users ADD COLUMN IF NOT EXISTS ""RoleId"" integer NULL;
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_users_roles_RoleId') THEN
                        ALTER TABLE users ADD CONSTRAINT ""FK_users_roles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES roles (""Id"") ON DELETE SET NULL;
                    END IF;
                END $$;
            ");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Nota de DDL actividades/usuarios/roles: {ex.Message}");
        }

        // 2. DML: Garantizar el sembrado de indicadores base de forma incondicional
        try
        {
            context.Database.ExecuteSqlRaw(@"
                INSERT INTO indicador (""Nombre"", ""Unidad"", ""Direccion"")
                VALUES
                    ('Tasa de deserción', '%', 'Descendente'),
                    ('Tasa de aprobación', '%', 'Ascendente'),
                    ('Publicaciones indexadas Scopus', 'artículos', 'Ascendente'),
                    ('Tiempo promedio de graduación', 'semestres', 'Descendente')
                ON CONFLICT (""Nombre"") DO NOTHING;
            ");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Nota de DML indicadores: {ex.Message}");
        }

        try
        {
            // 3. Sembrado de Programas Académicos
            if (!context.Programas.Any())
            {
                var programas = new[]
                {
                    new Programa { Id = 1, Nombre = "Ingeniería de Sistemas", Activo = true },
                    new Programa { Id = 2, Nombre = "Ingeniería Industrial", Activo = true },
                    new Programa { Id = 3, Nombre = "Ingeniería Electrónica", Activo = true }
                };
                context.Programas.AddRange(programas);
                context.SaveChanges();
            }

            // 4. Sembrado de Períodos Académicos
            if (!context.PeriodoAcademicos.Any())
            {
                var periodos = new List<PeriodoAcademico>();
                int idCounter = 1;
                for (short anio = 2025; anio >= 2018; anio--)
                {
                    periodos.Add(new PeriodoAcademico { Id = idCounter++, Anio = anio, Semestre = Semestre.I });
                    if (anio > 2018 || anio == 2025)
                    {
                        periodos.Add(new PeriodoAcademico { Id = idCounter++, Anio = anio, Semestre = Semestre.II });
                    }
                }
                context.PeriodoAcademicos.AddRange(periodos);
                context.SaveChanges();
            }

            // 5. Sembrado de Seguimiento de Cohortes
            if (!context.SeguimientosCohorte.Any())
            {
                var cohortes = new List<SeguimientoCohorte>();
                int idCounter = 1;

                for (int programaId = 1; programaId <= 3; programaId++)
                {
                    for (int periodoId = 1; periodoId <= 5; periodoId++)
                    {
                        for (int sem = 1; sem <= 10; sem++)
                        {
                            int ingresaron = 60;
                            int desertores = (sem * 2) + 3;
                            int continuaron = Math.Max(0, ingresaron - desertores - (sem > 8 ? 20 : 0));
                            int graduados = sem >= 9 ? 20 : 0;

                            cohortes.Add(new SeguimientoCohorte
                            {
                                Id = idCounter++,
                                ProgramaId = programaId,
                                PeriodoCohorteId = periodoId,
                                SemestreSeguimiento = sem,
                                Ingresaron = ingresaron,
                                Continuaron = continuaron,
                                Cancelaciones = 2,
                                Repitentes = 3,
                                CambiosPrograma = 1,
                                Desertores = desertores,
                                Graduados = graduados
                            });
                        }
                    }
                }
                context.SeguimientosCohorte.AddRange(cohortes);
                context.SaveChanges();
            }

            // 6. Sembrado de Seguimiento de Egresados
            if (!context.SeguimientosEgresado.Any())
            {
                var egresados = new List<SeguimientoEgresado>();
                int idCounter = 1;

                for (int programaId = 1; programaId <= 3; programaId++)
                {
                    for (short anio = 2020; anio <= 2024; anio++)
                    {
                        egresados.Add(new SeguimientoEgresado
                        {
                            Id = idCounter++,
                            ProgramaId = programaId,
                            AnioGraduacion = anio,
                            TotalEgresados = 45,
                            Empleados = 38,
                            EmpleadosRelacionadosCarrera = 32,
                            EmpleadosNoRelacionadosCarrera = 6,
                            TiempoPromedioConseguirEmpleoMeses = 3.5m,
                            ContratoIndefinido = 25,
                            ContratoTerminoFijo = 8,
                            ContratoPrestacionServicios = 5,
                            ContratoOtro = 0,
                            ContinuanEstudios = 7
                        });
                    }
                }
                context.SeguimientosEgresado.AddRange(egresados);
                context.SaveChanges();
            }

            // 5. Sembrado de permisos del sistema
            if (!context.Permissions.Any())
            {
                var systemPermissions = new List<Permission>
                {
                    // Indicadores
                    new() { Code = "INDICATORS_VIEW", Name = "Ver Indicadores Académicos", Module = "Indicadores", Description = "Permite ver el dashboard y gráficas de indicadores académicos" },
                    new() { Code = "INDICATORS_UPLOAD", Name = "Cargar Datos de Indicadores", Module = "Indicadores", Description = "Permite subir archivos Excel para actualización de indicadores" },
                    // Actividades
                    new() { Code = "ACTIVITIES_VIEW", Name = "Ver Actividades", Module = "Actividades", Description = "Permite consultar actividades institucionales" },
                    new() { Code = "ACTIVITIES_CREATE", Name = "Crear Actividades", Module = "Actividades", Description = "Permite registrar nuevas actividades académicas o de extensión" },
                    new() { Code = "ACTIVITIES_EDIT", Name = "Editar Actividades", Module = "Actividades", Description = "Permite modificar datos de actividades y adjuntar evidencias" },
                    new() { Code = "ACTIVITIES_DELETE", Name = "Eliminar Actividades", Module = "Actividades", Description = "Permite remover registros de actividades" },
                    // Metas
                    new() { Code = "GOALS_VIEW", Name = "Ver Metas", Module = "Metas", Description = "Permite consultar las metas institucionales y su avance" },
                    new() { Code = "GOALS_MANAGE", Name = "Gestionar Metas", Module = "Metas", Description = "Permite crear y actualizar metas institucionales" },
                    // Seguridad
                    new() { Code = "ROLES_MANAGE", Name = "Gestionar Roles y Permisos", Module = "Seguridad", Description = "Permite crear, editar, eliminar roles y asignar permisos" },
                    new() { Code = "USERS_MANAGE", Name = "Gestionar Usuarios", Module = "Seguridad", Description = "Permite asignar roles y administrar cuentas de usuario" }
                };

                context.Permissions.AddRange(systemPermissions);
                context.SaveChanges();
            }

            // 6. Sembrado de roles del sistema
            if (!context.Roles.Any())
            {
                var allPermissions = context.Permissions.ToList();

                // Rol Administrador (Todos los permisos)
                var adminRole = new Role
                {
                    Name = "Administrador",
                    Description = "Acceso completo a todos los módulos y configuración del sistema",
                    IsSystemRole = true,
                    CreatedAt = DateTime.UtcNow
                };
                foreach (var p in allPermissions)
                {
                    adminRole.RolePermissions.Add(new RolePermission { PermissionId = p.Id });
                }

                // Rol Coordinador
                var coordRole = new Role
                {
                    Name = "Coordinador",
                    Description = "Gestión de indicadores, actividades y metas del programa",
                    IsSystemRole = true,
                    CreatedAt = DateTime.UtcNow
                };
                var coordCodes = new HashSet<string> { "INDICATORS_VIEW", "INDICATORS_UPLOAD", "ACTIVITIES_VIEW", "ACTIVITIES_CREATE", "ACTIVITIES_EDIT", "GOALS_VIEW", "GOALS_MANAGE" };
                foreach (var p in allPermissions.Where(x => coordCodes.Contains(x.Code)))
                {
                    coordRole.RolePermissions.Add(new RolePermission { PermissionId = p.Id });
                }

                // Rol Docente
                var docRole = new Role
                {
                    Name = "Docente",
                    Description = "Registro y consulta de actividades académicas e indicadores",
                    IsSystemRole = true,
                    CreatedAt = DateTime.UtcNow
                };
                var docCodes = new HashSet<string> { "INDICATORS_VIEW", "ACTIVITIES_VIEW", "ACTIVITIES_CREATE", "ACTIVITIES_EDIT", "GOALS_VIEW" };
                foreach (var p in allPermissions.Where(x => docCodes.Contains(x.Code)))
                {
                    docRole.RolePermissions.Add(new RolePermission { PermissionId = p.Id });
                }

                // Rol Consultor
                var consultRole = new Role
                {
                    Name = "Consultor",
                    Description = "Acceso de solo lectura a métricas e informes",
                    IsSystemRole = false,
                    CreatedAt = DateTime.UtcNow
                };
                var consultCodes = new HashSet<string> { "INDICATORS_VIEW", "ACTIVITIES_VIEW", "GOALS_VIEW" };
                foreach (var p in allPermissions.Where(x => consultCodes.Contains(x.Code)))
                {
                    consultRole.RolePermissions.Add(new RolePermission { PermissionId = p.Id });
                }

                context.Roles.AddRange(adminRole, coordRole, docRole, consultRole);
                context.SaveChanges();
            }

            // 7. Sembrado de usuario administrador inicial
            var adminDbRole = context.Roles.FirstOrDefault(r => r.Name == "Administrador");

            if (!context.Users.Any())
            {
                var hasher = new AcademicTrack.Application.Auth.Services.PasswordHasher();
                var adminUser = new User
                {
                    Username = "admin",
                    Email = "admin@academictrack.edu",
                    FullName = "Administrador del Sistema",
                    Role = "Administrador",
                    RoleId = adminDbRole?.Id,
                    PasswordHash = hasher.HashPassword("Admin123*!"),
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                };

                context.Users.Add(adminUser);
                context.SaveChanges();
                Console.WriteLine("Usuario inicial administrador sembrado exitosamente (admin / Admin123*!).");
            }
            else if (adminDbRole != null)
            {
                // Asegurar que el usuario admin tenga su RoleId vinculado
                var existingAdmin = context.Users.FirstOrDefault(u => u.Username == "admin");
                if (existingAdmin != null && existingAdmin.RoleId == null)
                {
                    existingAdmin.RoleId = adminDbRole.Id;
                    existingAdmin.Role = adminDbRole.Name;
                    context.SaveChanges();
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error al sembrar datos: {ex.Message}");
        }
    }
}
