using AcademicTrack.Domain.Entities;
using AcademicTrack.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace AcademicTrack.Infrastructure.Persistence;

public static class DbInitializer
{
    public static void Seed(AcademicTrackDbContext context)
    {
        // 1. DDL: Garantizar la creación de tablas e índices de actividades de forma directa e incondicional
        try
        {
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS activity (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ProgramId"" integer NOT NULL,
                    ""Type"" character varying(30) NOT NULL,
                    ""Name"" character varying(300) NOT NULL,
                    ""Date"" date NOT NULL,
                    ""Location"" character varying(200) NULL,
                    ""Responsible"" character varying(150) NOT NULL,
                    ""ParticipatingProfessors"" text NULL,
                    ""ParticipatingStudents"" text NULL,
                    ""Description"" text NULL,
                    CONSTRAINT ""PK_activity"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_activity_programa_ProgramId"" FOREIGN KEY (""ProgramId"")
                        REFERENCES programa (""Id"") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS idx_activity_program ON activity (""ProgramId"");
                CREATE INDEX IF NOT EXISTS idx_activity_type ON activity (""Type"");
                CREATE INDEX IF NOT EXISTS idx_activity_date ON activity (""Date"");

                CREATE TABLE IF NOT EXISTS activity_evidence (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""ActivityId"" integer NOT NULL,
                    ""Url"" character varying(500) NOT NULL,
                    ""UploadDate"" date NOT NULL,
                    CONSTRAINT ""PK_activity_evidence"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_activity_evidence_activity_ActivityId"" FOREIGN KEY (""ActivityId"")
                        REFERENCES activity (""Id"") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS idx_activity_evidence_activity ON activity_evidence (""ActivityId"");
            ");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Nota de DDL actividades: {ex.Message}");
        }

        // 2. DML: Garantizar el sembrado de indicadores base de forma incondicional
        try
        {
            context.Database.ExecuteSqlRaw(@"
                INSERT INTO indicador (""Nombre"", ""Unidad"", ""Direccion"")
                VALUES
                    ('Tasa de deserción', '%', 'Descendente'),
                    ('Tasa de aprobación', '%', 'Ascendente'),
                    ('Publicaciones indexadas Scopus', 'artículos', 'Ascendente'),
                    ('Tiempo promedio de graduación', 'semestres', 'Descendente')
                ON CONFLICT (""Nombre"") DO NOTHING;
            ");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Nota de DML indicadores: {ex.Message}");
        }

        try
        {
            // 3. Sembrado de Programas Académicos
            if (!context.Programas.Any())
            {
                var programas = new[]
                {
                    new Programa { Id = 1, Nombre = "Ingeniería de Sistemas", Activo = true },
                    new Programa { Id = 2, Nombre = "Ingeniería Industrial", Activo = true },
                    new Programa { Id = 3, Nombre = "Ingeniería Electrónica", Activo = true }
                };
                context.Programas.AddRange(programas);
                context.SaveChanges();
            }

            // 4. Sembrado de Períodos Académicos
            if (!context.PeriodoAcademicos.Any())
            {
                var periodos = new List<PeriodoAcademico>();
                int idCounter = 1;
                for (short anio = 2025; anio >= 2018; anio--)
                {
                    periodos.Add(new PeriodoAcademico { Id = idCounter++, Anio = anio, Semestre = Semestre.I });
                    if (anio > 2018 || anio == 2025)
                    {
                        periodos.Add(new PeriodoAcademico { Id = idCounter++, Anio = anio, Semestre = Semestre.II });
                    }
                }
                context.PeriodoAcademicos.AddRange(periodos);
                context.SaveChanges();
            }

            // 5. Sembrado de Seguimiento de Cohortes
            if (!context.SeguimientosCohorte.Any())
            {
                var cohortes = new List<SeguimientoCohorte>();
                int idCounter = 1;

                for (int programaId = 1; programaId <= 3; programaId++)
                {
                    for (int periodoId = 1; periodoId <= 5; periodoId++)
                    {
                        for (int sem = 1; sem <= 10; sem++)
                        {
                            int ingresaron = 60;
                            int desertores = (sem * 2) + 3;
                            int continuaron = Math.Max(0, ingresaron - desertores - (sem > 8 ? 20 : 0));
                            int graduados = sem >= 9 ? 20 : 0;

                            cohortes.Add(new SeguimientoCohorte
                            {
                                Id = idCounter++,
                                ProgramaId = programaId,
                                PeriodoCohorteId = periodoId,
                                SemestreSeguimiento = sem,
                                Ingresaron = ingresaron,
                                Continuaron = continuaron,
                                Cancelaciones = 2,
                                Repitentes = 3,
                                CambiosPrograma = 1,
                                Desertores = desertores,
                                Graduados = graduados
                            });
                        }
                    }
                }
                context.SeguimientosCohorte.AddRange(cohortes);
                context.SaveChanges();
            }

            // 6. Sembrado de Seguimiento de Egresados
            if (!context.SeguimientosEgresado.Any())
            {
                var egresados = new List<SeguimientoEgresado>();
                int idCounter = 1;

                for (int programaId = 1; programaId <= 3; programaId++)
                {
                    for (short anio = 2020; anio <= 2024; anio++)
                    {
                        egresados.Add(new SeguimientoEgresado
                        {
                            Id = idCounter++,
                            ProgramaId = programaId,
                            AnioGraduacion = anio,
                            TotalEgresados = 45,
                            Empleados = 38,
                            EmpleadosRelacionadosCarrera = 32,
                            EmpleadosNoRelacionadosCarrera = 6,
                            TiempoPromedioConseguirEmpleoMeses = 3.5m,
                            ContratoIndefinido = 25,
                            ContratoTerminoFijo = 8,
                            ContratoPrestacionServicios = 5,
                            ContratoOtro = 0,
                            ContinuanEstudios = 7
                        });
                    }
                }
                context.SeguimientosEgresado.AddRange(egresados);
                context.SaveChanges();
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error al sembrar datos: {ex.Message}");
        }
    }
}
