// <auto-generated />
using System;
using AcademicTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcademicTrack.Infrastructure.Migrations
{
    [DbContext(typeof(AcademicTrackDbContext))]
    [Migration("20260822071859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ActividadExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<int>("ComunidadBeneficiada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Coordinador")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LogroResultados")
                        .HasColumnType("text");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Anio" }, "idx_actividad_anio");

                    b.HasIndex(new[] { "ProgramaId" }, "idx_actividad_programa");

                    b.ToTable("actividad_extension", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ActividadExtensionVinculacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("integer");

                    b.Property<short>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("TipoActor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ActividadId" }, "idx_actividad_vinculacion_actividad");

                    b.HasIndex(new[] { "ActividadId", "TipoActor" }, "uq_actividad_vinculacion")
                        .IsUnique();

                    b.ToTable("actividad_extension_vinculacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCompleto")
                        .IsUnique();

                    b.ToTable("autor", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CiudadOPais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LogroResultados")
                        .HasColumnType("text");

                    b.Property<int?>("NumUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Vigencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProgramaId" }, "idx_convenio_programa");

                    b.HasIndex(new[] { "Tipo", "Estado" }, "idx_convenio_tipo_estado");

                    b.ToTable("convenio", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ConvenioVinculacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoActor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ConvenioId" }, "idx_convenio_vinculacion_convenio");

                    b.HasIndex(new[] { "ConvenioId", "TipoActor" }, "uq_convenio_vinculacion")
                        .IsUnique();

                    b.ToTable("convenio_vinculacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.GrupoInvestigacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticulosIndexados")
                        .HasColumnType("int");

                    b.Property<int?>("ArticulosRii")
                        .HasColumnType("int");

                    b.Property<int?>("ArticulosRini")
                        .HasColumnType("int");

                    b.Property<int?>("ArticulosRni")
                        .HasColumnType("int");

                    b.Property<int?>("ArticulosRnni")
                        .HasColumnType("int");

                    b.Property<string>("ClasificacionMinciencias")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int?>("LibrosCapitulos")
                        .HasColumnType("int");

                    b.Property<int?>("LibrosCompletos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<short?>("NumInvestigadores")
                        .HasColumnType("smallint");

                    b.Property<int?>("NumPatentes")
                        .HasColumnType("int");

                    b.Property<int?>("OtrosResultados")
                        .HasColumnType("int");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("integer");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TotalProductos")
                        .HasColumnType("int");

                    b.Property<int?>("TrabajosGradoDoctorado")
                        .HasColumnType("int");

                    b.Property<int?>("TrabajosGradoMaestria")
                        .HasColumnType("int");

                    b.Property<int?>("TrabajosGradoPregrado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex(new[] { "ProgramaId" }, "idx_grupo_programa");

                    b.ToTable("grupo_investigacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.IndicadorMatricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Admitidos")
                        .HasColumnType("int");

                    b.Property<short?>("ExcluidosBajoRendimiento")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("GrupoReferenciaSaberPro")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("Inscritos")
                        .HasColumnType("int");

                    b.Property<int?>("MatriculadosPrimerCurso")
                        .HasColumnType("int");

                    b.Property<int>("MatriculadosTotal")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MediaNacionalSaberPro")
                        .HasColumnType("decimal(6,2)");

                    b.Property<short>("MovilidadEntranteInternacional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<short>("MovilidadEntranteNacional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<short>("MovilidadSalienteInternacional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<short>("MovilidadSalienteNacional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<decimal?>("PctCulminanCarrera")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("PctTasaDesercion")
                        .HasColumnType("decimal(6,4)");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PromedioSaberPro")
                        .HasColumnType("decimal(6,2)");

                    b.Property<short?>("ReintegroMatricula")
                        .HasColumnType("smallint");

                    b.Property<short?>("RetiradosCancelacion")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("TasaAbsorcion")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("TasaDesercionSpadies")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("TasaSelectividad")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("TotalGraduados")
                        .HasColumnType("int");

                    b.Property<short?>("TransferenciaExterna")
                        .HasColumnType("smallint");

                    b.Property<short?>("TransferenciaInterna")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoId");

                    b.HasIndex(new[] { "ProgramaId", "PeriodoId" }, "idx_indicador_programa_periodo")
                        .IsUnique();

                    b.ToTable("indicador_matricula", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.Innovacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("AplicacionUso")
                        .HasColumnType("text");

                    b.Property<string>("ComunidadBeneficiaria")
                        .HasColumnType("text");

                    b.Property<string>("EntidadBeneficiada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date");

                    b.Property<string>("Impacto")
                        .HasColumnType("text");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("integer");

                    b.Property<bool>("TieneSoporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Anio" }, "idx_innovacion_anio");

                    b.HasIndex(new[] { "ProgramaId" }, "idx_innovacion_programa");

                    b.ToTable("innovacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.InnovacionVinculacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Interno");

                    b.Property<int>("InnovacionId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoActor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InnovacionId" }, "idx_innovacion_vinculacion_innovacion");

                    b.HasIndex(new[] { "InnovacionId", "TipoActor", "Condicion" }, "uq_innovacion_vinculacion")
                        .IsUnique();

                    b.ToTable("innovacion_vinculacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.LineaInvestigacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GrupoId" }, "idx_linea_grupo");

                    b.ToTable("linea_investigacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.PeriodoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Anio", "Semestre")
                        .IsUnique();

                    b.ToTable("periodo_academico", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.Programa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoSnies")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Facultad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("programa", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ProyectoInvestigacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("AnioInicio")
                        .HasColumnType("smallint");

                    b.Property<string>("ComunidadBeneficiada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<string>("InvestigadorPrincipal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("LineaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ProductosGenerados")
                        .HasColumnType("text");

                    b.Property<string>("UrlProducto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Vigente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("LineaId");

                    b.HasIndex(new[] { "GrupoId" }, "idx_proyecto_grupo");

                    b.HasIndex(new[] { "Vigente" }, "idx_proyecto_vigente")
                        .HasFilter("\"Vigente\" = true");

                    b.ToTable("proyecto_investigacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ProyectoInvestigacionVinculacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoActor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProyectoId" }, "idx_proyecto_vinculacion_proyecto");

                    b.HasIndex(new[] { "ProyectoId", "TipoActor" }, "uq_proyecto_vinculacion")
                        .IsUnique();

                    b.ToTable("proyecto_investigacion_vinculacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("BaseIndexacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cuartil")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Indexada")
                        .HasColumnType("boolean");

                    b.Property<string>("ReferenciaCompleta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPublicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Anio" }, "idx_publicacion_anio");

                    b.HasIndex(new[] { "GrupoId" }, "idx_publicacion_grupo");

                    b.ToTable("publicacion", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.PublicacionAutor", b =>
                {
                    b.Property<int>("PublicacionId")
                        .HasColumnType("integer");

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<short?>("Orden")
                        .HasColumnType("smallint");

                    b.HasKey("PublicacionId", "AutorId");

                    b.HasIndex(new[] { "AutorId" }, "idx_publicacionautor_autor");

                    b.ToTable("publicacion_autor", (string)null);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ActividadExtension", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ActividadExtensionVinculacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.ActividadExtension", null)
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.Convenio", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ConvenioVinculacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.Convenio", null)
                        .WithMany()
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.GrupoInvestigacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.IndicadorMatricula", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.PeriodoAcademico", null)
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademicTrack.Domain.Entities.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.Innovacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.InnovacionVinculacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.Innovacion", null)
                        .WithMany()
                        .HasForeignKey("InnovacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.LineaInvestigacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.GrupoInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ProyectoInvestigacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.GrupoInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicTrack.Domain.Entities.LineaInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.ProyectoInvestigacionVinculacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.ProyectoInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.Publicacion", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.GrupoInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademicTrack.Domain.Entities.PublicacionAutor", b =>
                {
                    b.HasOne("AcademicTrack.Domain.Entities.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademicTrack.Domain.Entities.Publicacion", null)
                        .WithMany()
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
