CREATE TABLE activity (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProgramId" integer NOT NULL,
    "Type" character varying(30) NOT NULL,
    "Name" character varying(300) NOT NULL,
    "Date" date NOT NULL,
    "Location" character varying(200) NULL,
    "Responsible" character varying(150) NOT NULL,
    "ParticipatingProfessors" text NULL,
    "ParticipatingStudents" text NULL,
    "Description" text NULL,
    CONSTRAINT "PK_activity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_activity_programa_ProgramId" FOREIGN KEY ("ProgramId")
        REFERENCES programa ("Id") ON DELETE RESTRICT
);

CREATE INDEX idx_activity_program ON activity ("ProgramId");
CREATE INDEX idx_activity_type ON activity ("Type");
CREATE INDEX idx_activity_date ON activity ("Date");

CREATE TABLE activity_evidence (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ActivityId" integer NOT NULL,
    "Url" character varying(500) NOT NULL,
    "UploadDate" date NOT NULL,
    CONSTRAINT "PK_activity_evidence" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_activity_evidence_activity_ActivityId" FOREIGN KEY ("ActivityId")
        REFERENCES activity ("Id") ON DELETE CASCADE
);

CREATE INDEX idx_activity_evidence_activity ON activity_evidence ("ActivityId");
